version: '3'

services:
  frontend:
    image: node:alpine
    container_name: vue_app
    build: ./ # Ruta al Dockerfile del backend
    ports:
      - "5173:3000"
    command: sh -c "npm install && npm run dev"
    networks:
      backend_app-network:
          ipv4_address: 11.0.0.13
networks:
  backend_app-network:
    external: true