version: '3'

services:
  frontend:
    image: node:alpine
    container_name: vue_app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5173:3000"
    command: sh -c "npm install && npm run dev -- --port 3000"
