version: '3'

services:
  frontend:
    image: node:alpine
    container_name: vue_app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3005:5173"
    command: sh -c "npm install && npm run dev"
