version: '3'

services:
  frontend:
    container_name: vue_app
    build: ./ # Ruta al Dockerfile del backend
    ports:
      - "2000:80"
    networks:
      backend_app-network:
          ipv4_address: 11.0.0.13
networks:
  backend_app-network:
    external: true